### PR TITLE
fixed remaining bbug in RemoteSynchronizer

### LINKED ISSUE #5: Fix Blocker Bugs
@rrcomtech @ronnyporsch @pcprinz 

In order to improve comprehensibility, maintainability and overall quality 

* **blocker bugs** detected by SonarQube 

need to be removed in the *backend* subproject.

### PR DESCRIPTION
**Pull request by achillease**

### CODE REVIEW

File: backend/src/main/java/de/btu/swt/backend/version/git_sync/RemoteSynchronizer.java [hunk 1]
```diff
@@ -171,28 +174,28 @@ public void commitPullAndPushChanges(File[] files, String commitMessage, User us
...
+                }
+                fileWriter.write(String.join(" &nbsp; ", exports));
+                fileWriter.write(" |\n");
             }
-            fileWriter.write(String.join(" &nbsp; ", exports));
-            fileWriter.write(" |\n");
+            fileWriter.flush();
         }
-        fileWriter.flush();
-        fileWriter.close();
```
Comment (schubmat) [inline backend/src/main/java/de/btu/swt/backend/version/git_sync/RemoteSynchronizer.java:195]: @pcprinz as far as I can see, the `fileWriter` does not need to be closed anymore as it is incorporated into the try block, right?

**Review by schubmat — COMMENTED** [review]
Looks good. I just want to be sure, that I understood the corresponding change correctly (cf. my code comment)
